### PR TITLE
Fix/6

### PR DESCRIPTION
**Pull request by xross**

### CODE REVIEW

**Review by DaveAtkinsonXMOS — COMMENTED** [review]
The PR says that Build.pl is an empty file. Is this correct?

**Comment by xross** [comment]
> The PR says that Build.pl is an empty file. Is this correct?

That odd, GitHub reports file size change 100644 → 100755

All I did was change the perm of the file..

**Comment by xross** [comment]
Content is still there if I look a the PR branch: https://github.com/xmos/test_support/blob/fix/6/Build.pl

Looks like a GitHub web bug

**Comment by xross** [comment]
Note, this will break lib_xud tests, lib_xud PR incoming..

**Review by DaveAtkinsonXMOS — APPROVED** [review]
Looks good then...

**Review by kevinyeungxmos — APPROVED** [review]

**Pull request merged**
